- hosts: quiz_server
  become: yes
  vars:
    nodejs_version: "22"
    app_dir: "/root/app"

  tasks:
    - name: Update apt cache and install curl, git, nodejs prerequisites
      apt:
        name:
          - curl
          - git
        update_cache: yes
        state: present
      retries: 5
      delay: 5
      register: result_apt
      until: result_apt is succeeded

    - name: Add NodeSource repository for Node.js {{ nodejs_version }}
      shell: curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | bash -
      args:
        executable: /bin/bash
      register: nodesource_script
      changed_when: "'Node.js' in nodesource_script.stdout or 'nodesource' in nodesource_script.stdout"

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
      retries: 5
      delay: 5
      register: result_node
      until: result_node is succeeded

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Clone the application repository
      git:
        repo: https://github.com/SohaibMhd745/webSocketApplication.git
        dest: "{{ app_dir }}"
        version: main

    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"
        production: yes

    - name: Start the application with pm2
      shell: pm2 start npm --name quiz-socketio -- run start
      args:
        chdir: "{{ app_dir }}"

    - name: Save PM2 process list
      shell: pm2 save

    - name: Setup PM2 to start on boot
      shell: pm2 startup systemd -u root --hp /root