- hosts: quiz_server
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install curl and git
      apt:
        name:
          - curl
          - git
        state: present

    - name: Install Node.js (version 18)
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Clone application repository
      git:
        repo: https://github.com/SohaibMhd745/webSocketApplication.git
        dest: /root/app
        version: main

    - name: Install npm dependencies
      npm:
        path: /root/app
        production: yes

    - name: Start the application
      shell: npm run start
      args:
        chdir: /root/app