name: Deploy full stack application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Create private key file
        run: |
          mkdir -p infra
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > infra/id_rsa
          chmod 600 infra/id_rsa

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_ssh_pub_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_ssh_key_path: "./id_rsa"
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Get Droplet IP
        id: get_ip
        run: |
          ip=$(terraform output -raw droplet_ip)
          echo "DROPLET_IP=$ip" >> $GITHUB_ENV
        working-directory: infra

      - name: Generate Ansible inventory
        run: |
          echo "[quiz_server]" > infra/hosts.ini
          echo "${DROPLET_IP} ansible_user=root ansible_ssh_private_key_file=infra/id_rsa" >> infra/hosts.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i infra/hosts.ini infra/playbook.yml