name: Lint Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint
        working-directory: infra

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Check Terraform format
        run: terraform fmt -check -recursive
        working-directory: infra

      - name: Validate Terraform files
        run: terraform validate
        working-directory: infra